"""
Investment Research Agent — Main Orchestrator
==============================================
A 6-step multi-step LLM agent that produces a professional equity research brief
from a single natural-language query.

Chain overview:
  Step 1  LLM   — Parse raw query → {ticker, focus, questions, horizon}
  Step 2  TOOL  — yfinance → real financial metrics + news headlines
  Step 3  LLM   — Fundamental analysis → {valuation, strengths, weaknesses, red_flags}
  Step 4  LLM   — Investment thesis → {bull_case, bear_case, recommendation}
  Step 5  LLM   — Stress test → {challenged_assumptions, risk_rating, scenarios}
  Step 6  LLM   — Final report → polished Markdown research brief

Usage:
  python agent.py "Analyse Apple stock for long-term growth investment"
  python agent.py "Is Tesla a good buy right now? Focus on risk."
  python agent.py "NVDA value or overvalued?"
"""

import json
import os
import sys
from datetime import datetime

from utils import get_client
from steps import (
    step1_parse_query,
    step2_fetch_financial_data,
    step3_fundamental_analysis,
    step4_investment_thesis,
    step5_critique_thesis,
    step6_generate_report,
)

OUTPUT_DIR = "output"


# ──────────────────────────────────────────────
# State initialisation
# ──────────────────────────────────────────────

def init_state(user_query: str) -> dict:
    return {
        "user_query": user_query,
        # Populated by each step:
        "parsed_query": None,       # Step 1
        "financial_data": None,     # Step 2
        "fundamental_analysis": None,  # Step 3
        "investment_thesis": None,  # Step 4
        "thesis_critique": None,    # Step 5
        "final_report": None,       # Step 6
        # Metadata
        "tool_call_success": False,
        "run_timestamp": datetime.now().isoformat(),
    }


# ──────────────────────────────────────────────
# Output: save report + full state to disk
# ──────────────────────────────────────────────

def save_outputs(state: dict) -> tuple[str, str]:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    ticker = (state.get("financial_data") or {}).get("ticker", "UNKNOWN")
    company = (state.get("financial_data") or {}).get("company_name", ticker)

    # ── Markdown report ──
    md_path = os.path.join(OUTPUT_DIR, f"report_{ticker}_{timestamp}.md")
    pq = state.get("parsed_query") or {}
    thesis = state.get("investment_thesis") or {}
    critique = state.get("thesis_critique") or {}

    md_content = f"""# Equity Research Brief: {company} ({ticker})

**Generated:** {datetime.now().strftime("%B %d, %Y %H:%M")}
**Analysis Focus:** {pq.get('analysis_focus', 'N/A')}
**Time Horizon:** {pq.get('time_horizon', 'N/A')}
**Recommendation:** {(thesis.get('recommended_action') or 'N/A').upper()}
**Risk Rating:** {(critique.get('final_risk_rating') or 'N/A').upper()}
**Thesis Validity Score:** {critique.get('thesis_validity_score', 'N/A')}/10
**Live Data Retrieved:** {'Yes' if state.get('tool_call_success') else 'No (degraded mode)'}

---

{state.get('final_report', '_Report generation failed._')}

---

## Appendix A — Raw Intermediate Outputs

<details>
<summary>Fundamental Analysis (Step 3)</summary>

```json
{json.dumps(state.get('fundamental_analysis'), indent=2)}
```
</details>

<details>
<summary>Investment Thesis (Step 4)</summary>

```json
{json.dumps(state.get('investment_thesis'), indent=2)}
```
</details>

<details>
<summary>Thesis Critique (Step 5)</summary>

```json
{json.dumps(state.get('thesis_critique'), indent=2)}
```
</details>

---
*This report was generated by an AI agent for educational purposes. Not financial advice.*
"""
    with open(md_path, "w") as f:
        f.write(md_content)

    # ── Full state JSON ──
    json_path = os.path.join(OUTPUT_DIR, f"state_{ticker}_{timestamp}.json")
    with open(json_path, "w") as f:
        json.dump(state, f, indent=2, default=str)

    return md_path, json_path


# ──────────────────────────────────────────────
# Main agent runner
# ──────────────────────────────────────────────

def run_agent(user_query: str) -> dict:
    print("=" * 55)
    print("  INVESTMENT RESEARCH AGENT")
    print("=" * 55)
    print(f"  Query: {user_query}\n")

    client = get_client()
    state = init_state(user_query)

    # ── Execute the chain ──────────────────────
    state = step1_parse_query(client, state)
    state = step2_fetch_financial_data(state)
    state = step3_fundamental_analysis(client, state)
    state = step4_investment_thesis(client, state)
    state = step5_critique_thesis(client, state)
    state = step6_generate_report(client, state)

    # ── Save outputs ───────────────────────────
    md_path, json_path = save_outputs(state)

    print(f"\n{'=' * 55}")
    print("  AGENT COMPLETE")
    print(f"{'=' * 55}")
    print(f"  Report : {md_path}")
    print(f"  State  : {json_path}")
    print()
    print(state["final_report"])

    return state


# ──────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        print("ERROR: Please provide a query as a command-line argument.")
        print()
        print('Example: python agent.py "Analyse Apple stock for long-term investment"')
        sys.exit(1)

    query = " ".join(sys.argv[1:])
    run_agent(query)
